Add functions for handling addresses and more prometheus metrics for the Relay
metacraft-labs/DendrETH pull request #385
Opened 2024-10-03 12:37 UTC by kkirkov

2024-10-07 14:44 UTC, EmilIvanichkovv requested changes
New utils from `feat(relay): Add new functions for handling addresses (3d581cc118c964531c353589c3f3e6137ad97f10) ` can live in dedicated module `libs/typescript/ts-utils/evm`

2024-10-07 14:46 UTC, EmilIvanichkovv commented on relay/implementations/publish_evm_transaction.ts
> +        );
This is smooth.

2024-10-07 14:48 UTC, EmilIvanichkovv reviewed
I guess more prometheus metrics = more good. Just one comment left

2024-10-07 14:48 UTC, EmilIvanichkovv commented on relay/utils/discord_monitor.ts
> +      const message = `<@&1285217827560620113> ⚠️ Alert: Contract on **${network}** hasn't been updated in ${delayInMinutes.toFixed(
This is how you tag a discord role? This is the ID of the role I guess?

2024-10-07 14:51 UTC, EmilIvanichkovv commented on libs/typescript/ts-utils/common-utils.ts
> +};
Would be nicer to use effect/schema, but I think it is not used yet at DendrETH

2024-10-08 07:07 UTC, kkirkov commented
> New utils from `feat(relay): Add new functions for handling addresses (3d581cc118c964531c353589c3f3e6137ad97f10) ` can live in dedicated module `libs/typescript/ts-utils/evm`

Thanks for the idea - it is done

2024-10-08 19:25 UTC, Dimo99 approved these changes

2024-10-09 11:19 UTC, EmilIvanichkovv approved these changes

2024-10-09 11:25 UTC, merged